import { GoogleGenAI } from "@google/genai";

export async function transformImage(
  base64Image: string,
  mimeType: string,
  stylePrompt: string
): Promise<string> {
  const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
  
  // Remove the data:image/png;base64, prefix if it exists
  const base64Data = base64Image.split(',')[1] || base64Image;

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            data: base64Data,
            mimeType: mimeType,
          },
        },
        {
          text: `Transform this image into the following style: ${stylePrompt}. Maintain the original composition and subject, but apply the visual characteristics of the requested style. Return only the edited image.`,
        },
      ],
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }

  throw new Error("No image was generated by the model.");
}
